"""Module/table configuration for survey data presence checks."""

DEFAULT_PROJECT_IDS = [
    "740d0859-5283-4912-9202-25a78d15f73a",
    "a99a1242-3d9b-4346-89c4-1220f49b7a32",
]

# Manual corrections for common typos or legacy names from requirements text.
TABLE_NAME_OVERRIDES = {
    "in_service_trainiing_plans": "in_service_training_plans",
    "external_training_reports": "external_trainings_reports",
    "recievables_registers": "receivables_registers",
    "safetymanagement": "safety_managements",
    "sanitation": "sanitations",
    "facilityperfomanceobservation": "facility_performance_observation",
}

TABLE_EXPECTED_RECORDS = {
    "action_plans": 1,
    "business_plans": 1,
    "budgets": 1,
    "in_service_trainiing_plans": 1,
    "work_schedules": 1,
    "qi_plans": 1,
    "external_training_reports": 1,
    "attendance_registers": 1,
    "payables_registers": 1,
    "recievables_registers": 1,
    "annual_malaria_prevention_plans": 1,
    "customer_care_programs": 1,
    "MonthlyDataReports": 1,
    "DataManagementSOPs": 1,
    "DataAccuracies": 8,
    "CompletenessOfOPDRegisters": 1,
    "MaternalAndNeonatalHealths": 1,
    "FacilityPerfomanceObservation": 2,
    "ClosingBalances": 1,
    "Insurances": 1,
    "IncomeReviews": 1,
    "PharmacyStockValues": 1,
    "Accounts": 1,
    "TransactionExpenseReviews": 3,
    "SurveyBasicInformations": 1,
    "OrganizationCharts": 1,
    "JobDescriptions": 9,
    "StaffInformations": 1,
    "FrequencyOfCommitteeMeetings": 1,
    "FocalPersons": 1,
    "AdditionalSuggestions": 15,
    "InformationDeliveryAndSupportSatisfactions": 15,
    "PatientSatisfactionBasicInfos": 15,
    "PatientRightsAndResponsibilitiess": 15,
    "PatientArrivalPerceptions": 15,
    "PharmacyReviews": 1,
    "ExpiredDrugsManagements": 1,
    "AdditionalPharmacyInformations": 1,
    "DispensaryManagements": 33,
    "StockManagements": 33,
    "PharmacyDrugs": 1,
    "SafetyManagement": 1,
    "Sanitation": 1,
    "Ancs": 1,
    "Vaccinations": 1,
    "FamilyPlannings": 1,
    "PharmacyStocks": 1,
    "DispensingPharmacies": 1,
    "Ncds": 1,
    "Cehos": 1,
    "Cashiers": 1,
    "Accountings": 1,
    "Laboratories": 1,
    "Titualaires": 1,
    "DataManagers": 1,
    "Arvs": 1,
    "Receptionists": 1,
    "ConsultationRooms": 1,
    "Matenities": 1,
    "Hospitalizations": 1,
    "Toilets": 1,
    "NoticeBoards": 1,
    "AncTreatmentGuidelines": 15,
    "AsthmaTreatmentGuidelines": 15,
    "CheckListTreatmentGuidelines": 1,
    "CoughTreatmentGuidelines": 15,
    "DiabetesTreatmentGuidelines": 15,
    "DiarrhoeaTreatmentGuidelines": 15,
    "FeverTreatmentGuidelines": 15,
    "HypertensionTreatmentGuidelines": 15,
    "InpatientsCareTreatmentGuidelines": 15,
    "MalariaTreatmentGuidelines": 15,
    "MaternityTreatmentGuidelines": 1,
    "PneumoniaTreatmentGuidelines": 15,
    "ReferralProcessTreatmentGuidelines": 15,
    "TreatmentGuidelines": 1,
    "DyslipidemiaTreatmentGuidelines": 15,
    "CardiomyopathyTreatmentGuidelines": 15,
    "AdmittedPatientsOutcomes": 15,
    "AsthmaClassifications": 15,
    "HypertensionTreatmentOutcomes": 15,
    "DiarrhoeaKeyPerformanceIndicators": 1,
    "MalariaKeyPerformanceIndicators": 1,
    "MalnutritionKeyPerformanceIndicators": 1,
    "PneumoniaKeyPerformanceIndicators": 1,
    "DiabetesKnowledgeOnHomeSelfManagements": 15,
    "HypertensionKnowledgeOnHomeSelfManagements": 15,
    "CardiomyopathyTreatmentOutcomes": 1,
    "HypertensionClearances": 1,
    "DiabetesClearances": 1,
    "NewDiabetesTreatmentOutcomes": 15,
    "DyslipidemiaTreatmentOutcomes": 15,
    "HypertensionNephropathyPrevalences": 1,
    "DiabetesNephropathyPrevalences": 1,
}

MODULES = {
    "Administration": [
        "action_plans",
        "business_plans",
        "budgets",
        "in_service_trainiing_plans",
        "work_schedules",
        "qi_plans",
        "external_training_reports",
        "attendance_registers",
        "payables_registers",
        "recievables_registers",
        "annual_malaria_prevention_plans",
        "customer_care_programs",
    ],
    "Data Management": [
        "MonthlyDataReports",
        "DataManagementSOPs",
        "DataAccuracies",
        "CompletenessOfOPDRegisters",
        "MaternalAndNeonatalHealths",
    ],
    "Facility Performance Observation": [
        "FacilityPerfomanceObservation",
    ],
    "Finance Management": [
        "ClosingBalances",
        "Insurances",
        "IncomeReviews",
        "PharmacyStockValues",
        "Accounts",
        "TransactionExpenseReviews",
    ],
    "General Information": [
        "SurveyBasicInformations",
        "OrganizationCharts",
        "JobDescriptions",
        "StaffInformations",
        "FrequencyOfCommitteeMeetings",
        "FocalPersons",
    ],
    "Patient Satisfaction": [
        "AdditionalSuggestions",
    ],
    "Pharmacy Management": [
        "PharmacyReviews",
        "ExpiredDrugsManagements",
        "AdditionalPharmacyInformations",
        "DispensaryManagements",
        "StockManagements",
    ],
    "Safety Management": [
        "SafetyManagement",
    ],
    "Sanitation": [
        "Sanitation",
    ],
    "Service Area Description": [
        "Ancs",
        "Vaccinations",
        "FamilyPlannings",
        "PharmacyStocks",
        "DispensingPharmacies",
        "Ncds",
        "Cehos",
        "Cashiers",
        "Accountings",
        "Laboratories",
        "Titualaires",
        "DataManagers",
        "Arvs",
        "Receptionists",
        "ConsultationRooms",
        "Matenities",
        "Hospitalizations",
        "Toilets",
        "NoticeBoards",
    ],
    "Treatment Guidelines Compliance": [
        "AncTreatmentGuidelines",
        "AsthmaTreatmentGuidelines",
        "CheckListTreatmentGuidelines",
        "CoughTreatmentGuidelines",
        "DiabetesTreatmentGuidelines",
        "DiarrhoeaTreatmentGuidelines",
        "FeverTreatmentGuidelines",
        "HypertensionTreatmentGuidelines",
        "InpatientsCareTreatmentGuidelines",
        "MalariaTreatmentGuidelines",
        "MaternityTreatmentGuidelines",
        "PneumoniaTreatmentGuidelines",
        "ReferralProcessTreatmentGuidelines",
        "TreatmentGuidelines",
        "DyslipidemiaTreatmentGuidelines",
        "CardiomyopathyTreatmentGuidelines",
    ],
    "Treatment Outcomes": [
        "AdmittedPatientsOutcomes",
        "AsthmaClassifications",
        "HypertensionTreatmentOutcomes",
        "DiarrhoeaKeyPerformanceIndicators",
        "MalariaKeyPerformanceIndicators",
        "MalnutritionKeyPerformanceIndicators",
        "PneumoniaKeyPerformanceIndicators",
        "DiabetesKnowledgeOnHomeSelfManagements",
        "HypertensionKnowledgeOnHomeSelfManagements",
        "CardiomyopathyTreatmentOutcomes",
        "HypertensionClearances",
        "DiabetesClearances",
        "NewDiabetesTreatmentOutcomes",
        "DyslipidemiaTreatmentOutcomes",
        "HypertensionNephropathyPrevalences",
        "DiabetesNephropathyPrevalences",
    ],
}

PROJECT_DATA_TABLES = [
    "projects",
    "project_questions_maps",
    "project_questions",
    "project_question_categories",
    "question_categories_maps",
]
